name: neo4j

services:
  neo4j:
    image: neo4j:5-community
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - neo4j

volumes:
  neo4j_data:
    name: dockge_neo4j_data
  neo4j_logs:
    name: dockge_neo4j_logs

networks:
  neo4j:
    name: dockge_neo4j_network
